### PR TITLE
feat: comp set for pulls

### PR DESCRIPTION
**Pull request by mshanemc**
### What does this PR do?
generate a componentSet for pulls from STL
this makes sure we resolve any source-backed components
it also happily makes forceignore work better

NUT here: https://github.com/salesforcecli/plugin-source/pull/471

### What issues does this PR fix or reference?
https://github.com/forcedotcom/cli/issues/1485
[@W-11047555@](https://gus.lightning.force.com/a07EE00000vj4ZuYAI)
https://github.com/forcedotcom/cli/issues/1471
[@W-11003710@](https://gus.lightning.force.com/a07EE00000v1JNUYA2)

### CODE REVIEW

**Review by WillieRuemmele — APPROVED** [review]
LGTM, do we want any UTs for this method, or a NUT in the plugin?

**Comment by mshanemc** [comment]
> LGTM, do we want any UTs for this method, or a NUT in the plugin?

yeps, those are here https://github.com/salesforcecli/plugin-source/pull/471

I'm updating the PR to make that clearer

**Review by shetzel — APPROVED** [review]
Approved, although I believe all public methods should have at least 1 unit test.

**Comment by cromwellryan** [comment]
@shetzel @mshanemc do we need a WI for a UT for this? Something that can give fast feedback in this repo vs running NUTS elsewhere?

**Pull request merged**
